= Building, Debugging and Testing on Ubuntu (WSL)

== Pre-requisite
* Install python version >= 3.8
+
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install python3
```
* Install `pip3`
+
```
sudo apt-get install -y python3-pip
```
* Install `pipx`
+
```
python3 -m pip install --user pipx
python3 -m pipx ensurepath
```
+
Running pipx ensurepath includes pipx in your PATH variable. In other words, this makes sure that entering pipx by itself will find the right executable.
+
https://dev.to/bowmanjd/how-do-i-install-a-python-command-line-tool-or-script-hint-pipx-3i2
* Install poetry
+
```
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
```
* Enable auto-completion for Oh-My-Zsh
+
```
mkdir $ZSH_CUSTOM/plugins/poetry
poetry completions zsh > $ZSH_CUSTOM/plugins/poetry/_poetry
```
+
Edit .zshrc and add `poetry` into `plugins(...)`
+
```
plugins(
    poetry
    ...
    )
```
* Run `vim ~/.poetry/bin/poetry` and replace `#!/usr/bin/env python` with `#!/usr/bin/env python3` if any, otherwise, simply insert `#!/usr/bin/env python3` as first line.

== Dependency packages

* Restore dependency packages
+
```
poetry install
```
* Add new package
+
```
poetry add new-package
```
* Add new package just as development dependency
+
```
poetry add new-package --dev
```
* Remove existing package
+
poetry remove existing-package
+
* Remove existing package from the development dependencies
+
```
poetry remove existing-package --dev
```

== Run

```
poetry run python3 src/bintweet CONSUMER_KEY CONSUMER_SECRET ACCESS_TOKEN ACCESS_TOKEN_SECRET
```

== Display help documentation for `bintweet`

```
poetry run python3 src/bintweet --help
```