name: run

on:
    schedule:
        - cron: "0 * * * *"

    workflow_dispatch:

jobs:
    run:
        name: ubuntu-latest
        runs-on: ubuntu-latest
        steps:
            # - name: Set up Go 1.15
            #   uses: actions/setup-go@v2
            #   with:
            #       go-version: ^1.15

            - name: Checkout bintweet repository
              uses: actions/checkout@v2

            - name: Setup go-task
              run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d

            - name: Setup poetry
              uses: Gr1N/setup-poetry@v4

            - name: Run bintweet
              run: ./bin/task run
              env:
                  CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
                  CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
