name: run

on:
    schedule:
        - cron: "0 * * * *"

    workflow_dispatch:

jobs:
    run:
        strategy:
            matrix:
                python-version: ["3.10"]
        name: run bintweet python program
        runs-on: ubuntu-latest
        steps:
            # - name: Set up Go 1.15
            #   uses: actions/setup-go@v2
            #   with:
            #       go-version: ^1.15

            - name: Checkout bintweet repository
              uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Setup go-task
              run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d

            - name: Setup poetry
              uses: Gr1N/setup-poetry@v8

            - name: Run bintweet
              run: ./bin/task run
              env:
                  CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
                  CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
                  BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
